# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[graph]
targets = []
all-features = false
no-default-features = false
features = []

[advisories]
# Ignore paste unmaintained warning - it's a proc-macro helper crate
# with no security issues, and is a transitive dependency
ignore = [
    "RUSTSEC-2024-0436",  # paste - unmaintained
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "MPL-2.0",
    "Zlib",
    "OpenSSL",
    "CDLA-Permissive-2.0",
    "NCSA",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["ISC", "MIT", "OpenSSL"], crate = "ring" },
    { allow = ["ISC", "MIT", "OpenSSL"], crate = "rustls-webpki" },
]

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
