name: Build (musl)

on:
  release:
    types: [published]

jobs:
  build-static:
    name: Build static library (musl)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: x86_64-unknown-linux-musl
          cache-on-failure: true

      - name: Install MUSL tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build staticlib
        run: cargo build --release --lib --target x86_64-unknown-linux-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-lib-rs-staticlib-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl/release/libsupabase.a
